import { Component } from "@angular/core";

@Component({
 selector: 'fd-list',
 templateUrl: './fooddata-list.component.html'
})
export class FoodDataComponent {
    pageTitle: string = "Food Data";
    foods: any[] = [
        {
            "Navn": "A38. acidophilus tykmælk",
            "Fnr/Cnr": 1291,
            "Svind": "0",
            "Energi. kJ": 283,
            "EnergiKcal": 68,
            "Proteinomregningsfaktor(NCF)": 6.38,
            "total-N": 0.765,
            "ProteinTotal": 4.9,
            "Protein. deklaration": 4.8,
            "Kulhydrat best. v/diff.": 4.5,
            "Kulhydrat": 4.5,
            "kulhydrat. deklaration": 4.6,
            "Tilsat sukker": "0",
            "Kostfibre": "0",
            "Fedt. total": 3.5,
            "Fedtsyrekonverteringsfaktor (FCF)": 0.945,
            "Alkohol": "0",
            "Aske": 0.9,
            "T�rstof": 13.7,
            "Vand": 86.3,
            "A-vitamin": 23.3,
            "Retinol": 22,
            "�-caroten": 15,
            "D-vitamin": 0.1,
            "D3 cholecalciferol": 0.1,
            "E-vitamin": 0.075,
            "alfa-tokoferol": 0.075,
            "K1-vitamin": "0",
            "B1-vitamin": 0.04,
            "B2-vitamin. riboflavin": 0.215,
            "Niacin": 1.22,
            "niacin": 0.105,
            "B6-vitamin": 0.041,
            "Pantothensyre": 0.305,
            "Biotin": 1.1,
            "Folat": 6.2,
            "B12-vitamin": 0.295,
            "C-vitamin": 0.3,
            "L-ascorbinsyre": 0.3,
            "Chlorid. Cl": 0.085,
            "Natrium. Na": 35.5,
            "Kalium. K": 153,
            "Calcium. Ca": 126,
            "Magnesium. Mg": 12.3,
            "Phosphor. P": 100,
            "Jern. Fe": 0.026,
            "Kobber. Cu": 0.015,
            "Zink. Zn": 0.54,
            "Jod. I": 9.05,
            "Mangan. Mn": 0.007,
            "Chrom. Cr": 0.09,
            "Selen. Se": 2.85,
            "Molybd�n. Mo": 5,
            "Nikkel. Ni": 0.385,
            "Cadmium. Cd": 0.002,
            "Bly. Pb": 0.089,
            "L-m�lkesyre": 0.91,
            "D-m�lkesyre": 0.05,
            "M�lkesyre. total": 0.96,
            "Citronsyre": 0.03,
            "Organiske syrer. tot.": 0.99,
            "Fructose": "0",
            "Galaktose": "0",
            "Glucose": "0",
            "Monosaccharider. total": "0",
            "Lactose": 3.52,
            "Maltose": "0",
            "Saccharose": "0",
            "Disaccharider. total": 3.52,
            "Andre sukkerarter": "0",
            "SukkerarterIalt": 3.52,
            "Stivelse": "0",
            "C4:0": 0.11,
            "C6:0": 0.085,
            "C8:0": 0.045,
            "C10:0": 0.11,
            "C12:0": 0.12,
            "C14:0": 0.335,
            "C15:0": 0.035,
            "C16:0": 0.885,
            "C18:0": 0.35,
            "C14:1.n-5": 0.03,
            "C16:1.n-7": 0.045,
            "C18:1.n-9": 0.515,
            "C18:1.n-7": 0.02,
            "C18:1.trans n-9": 0.105,
            "C18:2.n-6": 0.05,
            "C18:2.conj-A. udifferentieret": 0.015,
            "C18:2.trans. udifferentieret": 0.025,
            "C18:3.n-3": 0.02,
            "Andre fedtsyrer": 0.035,
            "Sum m�ttede": 2.075,
            "Sum monoum�ttede": 0.715,
            "Sum polyum�ttede": 0.11,
            "Fedtsyrer. total": 2.935,
            "Sum n-3 fedtsyrer": 0.02,
            "Sum n-6 fedtsyrer": 0.05,
            "Transfedtsyrer. total": 0.105,
            "Cholesterol": 14,
            "Isoleucin": 260,
            "Leucin": 505,
            "Lysin": 436,
            "Methionin": 122,
            "Cystin": 31,
            "Phenylalanin": 237,
            "Tyrosin": 237,
            "Threonin": 214,
            "Tryptofan": 67,
            "Valin": 344,
            "Arginin": 161,
            "Histidin": 130,
            "Alanin": 161,
            "Asparaginsyre": 390,
            "Glutaminsyre": 933,
            "Glycin": 107,
            "Prolin": 474,
            "Serin": 30
         },
         {
            "Navn": "A38. acidophilus tykmælk. med citronsaft (HISTORISK)",
            "Fnr/Cnr": 1307,
            "Svind": "0",
            "Energi. kJ": 315,
            "EnergiKcal": 75,
            "Proteinomregningsfaktor(NCF)": 6.38,
            "total-N": 0.765,
            "ProteinTotal": 4.9,
            "Protein. deklaration": 4.8,
            "Kulhydrat best. v/diff.": 8.7,
            "Kulhydrat": 6.4,
            "kulhydrat. deklaration": 6.5,
            "Tilsat sukker": 4,
            "Kostfibre": "0",
            "Fedt. total": 3.5,
            "Fedtsyrekonverteringsfaktor (FCF)": 0.945,
            "Alkohol": "0",
            "Aske": 0.8,
            "T�rstof": 15.5,
            "Vand": 84.5,
            "A-vitamin": 31.3,
            "Retinol": 30,
            "�-caroten": 15,
            "D-vitamin": 0.1,
            "D3 cholecalciferol": 0.1,
            "E-vitamin": 0.09,
            "alfa-tokoferol": 0.09,
            "K1-vitamin": "0",
            "B1-vitamin": 0.037,
            "B2-vitamin. riboflavin": 0.18,
            "Niacin": 1.21,
            "niacin": 0.088,
            "B6-vitamin": 0.043,
            "Pantothensyre": 0.28,
            "Biotin": 1.8,
            "Folat": 6.2,
            "B12-vitamin": 0.23,
            "C-vitamin": 0.2,
            "L-ascorbinsyre": 0.2,
            "Natrium. Na": 35.5,
            "Kalium. K": 153,
            "Calcium. Ca": 126,
            "Magnesium. Mg": 12.3,
            "Phosphor. P": 100,
            "Jern. Fe": 0.05,
            "Kobber. Cu": 0.01,
            "Zink. Zn": 0.44,
            "Jod. I": 10.7,
            "Mangan. Mn": 0.01,
            "Chrom. Cr": 0.052,
            "Selen. Se": 1.3,
            "Molybd�n. Mo": 5,
            "Nikkel. Ni": 0.705,
            "Cadmium. Cd": 0.002,
            "Bly. Pb": 0.089,
            "L-m�lkesyre": 0.91,
            "D-m�lkesyre": 0.05,
            "M�lkesyre. total": 0.96,
            "Citronsyre": 0.03,
            "Organiske syrer. tot.": 0.99,
            "Fructose": "0",
            "Galaktose": "0",
            "Glucose": "0",
            "Monosaccharider. total": "0",
            "Lactose": 3.52,
            "Maltose": "0",
            "Saccharose": 3.98,
            "Disaccharider. total": 7.5,
            "Andre sukkerarter": "0",
            "SukkerarterIalt": 7.5,
            "Stivelse": "0",
            "C4:0": 0.117,
            "C6:0": 0.075,
            "C8:0": 0.049,
            "C10:0": 0.107,
            "C12:0": 0.134,
            "C14:0": 0.381,
            "C16:0": 1.023,
            "C18:0": 0.348,
            "C14:1.n-5": 0.049,
            "C16:1.n-7": 0.075,
            "C18:1.n-9": 0.765,
            "C20:1.n-11": 0.039,
            "C18:2.n-6": 0.072,
            "C18:3.n-3": 0.026,
            "Sum m�ttede": 2.234,
            "Sum monoum�ttede": 0.928,
            "Sum polyum�ttede": 0.098,
            "Fedtsyrer. total": 3.26,
            "Sum n-3 fedtsyrer": 0.026,
            "Sum n-6 fedtsyrer": 0.072,
            "Transfedtsyrer. total": "0",
            "Cholesterol": 14,
            "Isoleucin": 260,
            "Leucin": 505,
            "Lysin": 436,
            "Methionin": 122,
            "Cystin": 31,
            "Phenylalanin": 237,
            "Tyrosin": 237,
            "Threonin": 214,
            "Tryptofan": 67,
            "Valin": 344,
            "Arginin": 161,
            "Histidin": 130,
            "Alanin": 161,
            "Asparaginsyre": 390,
            "Glutaminsyre": 933,
            "Glycin": 107,
            "Prolin": 474,
            "Serin": 12
         },
         {
            "Navn": "Ab-mælk. syrnet sødmælk",
            "Fnr/Cnr": 1278,
            "Svind": "0",
            "Energi. kJ": 265,
            "EnergiKcal": 63,
            "Proteinomregningsfaktor(NCF)": 6.38,
            "total-N": 0.549,
            "ProteinTotal": 3.5,
            "Protein. deklaration": 3.4,
            "Kulhydrat best. v/diff.": 4.5,
            "Kulhydrat": 4.5,
            "kulhydrat. deklaration": 4.6,
            "Tilsat sukker": "0",
            "Kostfibre": "0",
            "Fedt. total": 3.6,
            "Fedtsyrekonverteringsfaktor (FCF)": 0.945,
            "Alkohol": "0",
            "Aske": 0.8,
            "T�rstof": 12.4,
            "Vand": 87.6,
            "A-vitamin": 32.3,
            "Retinol": 31,
            "�-caroten": 16,
            "D-vitamin": 0.1,
            "D3 cholecalciferol": 0.1,
            "E-vitamin": 0.09,
            "alfa-tokoferol": 0.09,
            "B1-vitamin": 0.045,
            "B2-vitamin. riboflavin": 0.203,
            "Niacin": 0.87,
            "niacin": 0.087,
            "B6-vitamin": 0.038,
            "Pantothensyre": 0.28,
            "Biotin": 1.8,
            "Folat": 6,
            "B12-vitamin": 0.18,
            "C-vitamin": 0.3,
            "L-ascorbinsyre": 0.3,
            "Natrium. Na": 35.5,
            "Kalium. K": 153,
            "Calcium. Ca": 127,
            "Magnesium. Mg": 12.7,
            "Phosphor. P": 95,
            "Jern. Fe": 0.05,
            "Kobber. Cu": 0.015,
            "Zink. Zn": 0.54,
            "Jod. I": 10.7,
            "Mangan. Mn": 0.009,
            "Chrom. Cr": 0.052,
            "Selen. Se": 1.3,
            "Molybd�n. Mo": 3,
            "Nikkel. Ni": 2,
            "Kviks�lv. Hg": 0.03,
            "Arsen. As": 0.3,
            "Cadmium. Cd": 0.002,
            "Bly. Pb": 0.089,
            "L-m�lkesyre": 0.89,
            "D-m�lkesyre": 0.03,
            "Citronsyre": 0.02,
            "Organiske syrer. tot.": 0.94,
            "Fructose": "0",
            "Galaktose": 0.06,
            "Glucose": "0",
            "Monosaccharider. total": 0.06,
            "Lactose": 3.78,
            "Maltose": "0",
            "Saccharose": "0",
            "Disaccharider. total": 3.78,
            "SukkerarterIalt": 3.84,
            "Stivelse": "0",
            "(a)Hexoses": "0",
            "(b)Pentoses": "0",
            "(c)UronicAcids": "0",
            "Cellulose": "0",
            "Lignin": "0",
            "C4:0": 0.122,
            "C6:0": 0.078,
            "C8:0": 0.051,
            "C10:0": 0.112,
            "C12:0": 0.139,
            "C14:0": 0.398,
            "C16:0": 1.069,
            "C18:0": 0.364,
            "C14:1.n-5": 0.051,
            "C16:1.n-7": 0.078,
            "C18:1.n-9": 0.798,
            "C20:1.n-11": 0.041,
            "C18:2.n-6": 0.075,
            "C18:3.n-3": 0.027,
            "Sum m�ttede": 2.333,
            "Sum monoum�ttede": 0.968,
            "Sum polyum�ttede": 0.102,
            "Fedtsyrer. total": 3.403,
            "Sum n-3 fedtsyrer": 0.027,
            "Sum n-6 fedtsyrer": 0.075,
            "Transfedtsyrer. total": "0",
            "Cholesterol": 14,
            "Isoleucin": 192,
            "Leucin": 340,
            "Lysin": 302,
            "Methionin": 88,
            "Cystin": 21,
            "Phenylalanin": 170,
            "Tyrosin": 165,
            "Threonin": 143,
            "Tryptofan": 47,
            "Valin": 236,
            "Arginin": 121,
            "Histidin": 93,
            "Alanin": 115,
            "Asparaginsyre": 280,
            "Glutaminsyre": 664,
            "Glycin": 77,
            "Prolin": 329,
            "Serin": 60
         }
    ]
}